msbuild cyg/msys compatible

diff --git a/local/bin/msbuild b/local/bin/msbuild
--- a/local/bin/msbuild
+++ b/local/bin/msbuild
@@ -1,3 +1,16 @@
 #!/usr/bin/bash
 
-/mnt/c/Program\ Files/Microsoft\ Visual\ Studio/*/*/MSBuild/Current/Bin/MSBuild.exe -p:Configuration="Unicode Debug" -p:Platform="x64" -nologo -p:GenerateFullPaths=true "-clp:ForceConsoleColor;Summary" -verbosity:m -m $* | sed -e "s@\\\\@/@g" -e "s@C:/@/mnt/c/@g"
+if [ -d "/mnt/c" ]
+then
+    C_DIR="/mnt/c"
+else
+    if [ -d "/c" ]
+    then
+        C_DIR="/c"
+    else
+        echo "ERROR: No Windows drives mapped."
+        exit 1
+    fi
+fi
+
+${C_DIR}/Program\ Files/Microsoft\ Visual\ Studio/*/*/MSBuild/Current/Bin/MSBuild.exe -p:Platform="x64" -nologo -p:GenerateFullPaths=true "-clp:ForceConsoleColor" -verbosity:m -m $* | sed -e "s@\\\\@/@g" -e "s@C:/@${C_DIR}/@g"
